"""Generate CMake projects for the C++ code export (issue #333, phase 2).

After a build, every ``format="code"`` output directory of a C++ course
contains one compilable translation unit per deck (#333 phase 1), with any
deck-local headers copied alongside by the regular data-file copy. This
module adds a generated ``CMakeLists.txt`` to each such directory — one
executable target per deck — so students can open the directory as a CMake
project (VS Code, CLion, Visual Studio) and build any deck with real
compiler diagnostics, independent of the Jupyter kernels.

Deck-local headers need no CMake configuration: they sit next to the
translation units, and ``#include "..."`` searches the including file's
directory first.

Layout produced (one per language × kind, language is already a separate
course tree)::

    <Course>-<lang>/<Slides>/<Cpp>/<Kind>/CMakeLists.txt
                                          <01 Section>/<01 Deck>.cpp
"""

from __future__ import annotations

import logging
import re
import unicodedata
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING

from clm.core.course_files.notebook_file import NotebookFile
from clm.infrastructure.utils.path_utils import ext_for, output_specs

if TYPE_CHECKING:
    from clm.core.course import Course

logger = logging.getLogger(__name__)

CMAKELISTS_FILENAME = "CMakeLists.txt"


def cmake_identifier(text: str) -> str:
    """Fold *text* to a safe CMake identifier.

    ASCII-folds (``Einführung`` → ``einfuhrung``), lowercases, and collapses
    every other character run to ``_``. Returns ``deck`` for input that
    folds to nothing.
    """
    folded = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    ident = re.sub(r"[^A-Za-z0-9]+", "_", folded).strip("_").lower()
    return ident or "deck"


def deck_target_name(rel_path: str) -> str:
    """Derive a CMake target name from a deck's path relative to the project.

    ``"01 Einführung/03 Entwicklungsumgebungen.cpp"`` →
    ``"s01_03_entwicklungsumgebungen"``: section number (when present) keeps
    the targets sorted and grouped like the course material.
    """
    path = PurePosixPath(rel_path)
    name = cmake_identifier(path.stem)
    section = path.parent.name
    if section:
        section_number = re.match(r"(\d+)", section)
        prefix = (
            f"s{int(section_number.group(1)):02d}" if section_number else cmake_identifier(section)
        )
        name = f"{prefix}_{name}"
    if not re.match(r"[A-Za-z_]", name):
        name = f"deck_{name}"
    return name


def generate_cmakelists(project_name: str, deck_rel_paths: Sequence[str]) -> str:
    """Generate the ``CMakeLists.txt`` text for one code-output directory.

    One executable target per deck, deterministic order, duplicate target
    names disambiguated with a numeric suffix.
    """
    lines = [
        "# Generated by CLM — one executable target per slide deck.",
        "# Open this directory as a CMake project (VS Code, CLion, Visual Studio).",
        "",
        "cmake_minimum_required(VERSION 3.21)",
        f"project({cmake_identifier(project_name)} LANGUAGES CXX)",
        "",
        "set(CMAKE_CXX_STANDARD 20)",
        "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
        "",
        "if(MSVC)",
        "    # Slide sources are UTF-8; MSVC assumes the local codepage without this.",
        "    add_compile_options(/utf-8)",
        "endif()",
        "",
    ]
    used: dict[str, int] = {}
    for rel in sorted(deck_rel_paths):
        name = deck_target_name(rel)
        count = used.get(name, 0)
        used[name] = count + 1
        if count:
            name = f"{name}_{count + 1}"
        lines.append(f'add_executable({name} "{rel}")')
    return "\n".join(lines) + "\n"


@dataclass
class CodeProject:
    """The decks found in one code-output directory."""

    project_name: str
    decks: set[str] = field(default_factory=set)


def collect_cpp_code_outputs(course: Course) -> dict[Path, CodeProject]:
    """Find every C++ code-output directory with the decks it contains.

    Keys are the kind-root directories (``.../<Cpp>/<Kind>``); only code
    outputs that exist on disk are recorded, enumerating the same way the
    provenance manifest does (course files × output specs).
    """
    groups: dict[Path, CodeProject] = {}
    for target in course.output_targets:
        if not target.output_root.exists():
            continue
        for file in course.files:
            if not isinstance(file, NotebookFile):
                continue
            ext = ext_for("code", file.prog_lang)
            if ext != ".cpp":
                continue
            for lang, fmt, kind, output_dir in output_specs(
                course, target.output_root, file.skip_html, target=target
            ):
                if fmt != "code":
                    continue
                try:
                    out_path = file.output_dir(output_dir, lang) / file.file_name(lang, ext)
                except (KeyError, ValueError):
                    # e.g. a split-language source with no title for this
                    # language; that combination is simply not produced.
                    continue
                if not out_path.is_file():
                    continue
                group = groups.setdefault(
                    output_dir,
                    CodeProject(project_name=f"{course.output_dir_name[lang]} {kind}"),
                )
                group.decks.add(out_path.relative_to(output_dir).as_posix())
    return groups


def write_cmake_projects(course: Course) -> list[Path]:
    """Write one ``CMakeLists.txt`` per built C++ code-output directory.

    No-op for non-C++ courses. Only directories that actually contain code
    outputs get a project file. Returns the list of paths written.
    """
    if course.prog_lang != "cpp":
        return []
    written: list[Path] = []
    for kind_root, project in sorted(collect_cpp_code_outputs(course).items()):
        content = generate_cmakelists(project.project_name, sorted(project.decks))
        path = kind_root / CMAKELISTS_FILENAME
        path.write_text(content, encoding="utf-8")
        written.append(path)
        logger.info("Wrote %s (%d deck targets)", path, len(project.decks))
    return written
