"""Regression tests: committed generated images must not race their conversion.

DrawIO and PlantUML sources render into the *source* tree, at
``<topic>/img/<stem>.png`` (see :meth:`clm.core.course_files.image_file.
ImageFile.img_path`). The copy of that image into the output tree therefore has
to be scheduled *after* the conversion, which is what
``COPY_GENERATED_IMAGES_STAGE`` exists for.

The stage used to be chosen by asking whether the image existed on disk at load
time. That is the wrong question: course repos routinely *commit* the generated
PNGs so notebooks render on GitHub, and CLM's own ``test-data`` does the same.
Such an image exists at load time, so it was classified as pre-existing and
copied in stage 1 — concurrently with the conversion overwriting that very path.
Whichever finished last decided the bytes, so two consecutive builds of an
unchanged course produced different output.
"""

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from clm.core.course_files.duplicated_image_file import DuplicatedImageFile
from clm.core.course_files.shared_image_file import SharedImageFile
from clm.core.utils.execution_utils import (
    COPY_GENERATED_IMAGES_STAGE,
    FIRST_EXECUTION_STAGE,
)

# Topic ``some_topic_from_test_1`` carries all three interesting cases:
#   img/my_drawing.png  <- generated by drawio/my_drawing.drawio, and committed
#   img/my_diag.png     <- generated by pu/my_diag.pu, and committed
#   img/my_image.png    <- a genuinely static image, no generator
GENERATED_AND_COMMITTED = ("my_drawing.png", "my_diag.png")
STATIC_ONLY = "my_image.png"


@pytest.fixture
def mock_course():
    course = MagicMock()
    course.output_languages = None
    course.output_kinds = None
    course.name = {"de": "Mein-Kurs", "en": "My-Course"}
    course.image_mode = "duplicated"
    course.prog_lang = "python"
    return course


@pytest.fixture
def mock_topic(tmp_path):
    topic = MagicMock()
    topic.path = tmp_path
    topic.section = MagicMock(name={"de": "Sektion", "en": "Section"})
    return topic


@pytest.mark.parametrize("image_class", [SharedImageFile, DuplicatedImageFile])
class TestMarkGenerated:
    """``mark_generated`` must win over the file-exists heuristic."""

    def _make(self, image_class, course, topic, tmp_path, *, create: bool):
        img_path = tmp_path / "img" / "diagram.png"
        img_path.parent.mkdir(parents=True, exist_ok=True)
        if create:
            img_path.write_bytes(b"stale committed render")
        return image_class._from_path(course, img_path, topic)

    def test_existing_image_defaults_to_first_stage(
        self, image_class, mock_course, mock_topic, tmp_path
    ):
        image = self._make(image_class, mock_course, mock_topic, tmp_path, create=True)
        assert image.execution_stage == FIRST_EXECUTION_STAGE

    def test_marking_an_existing_image_moves_it_past_the_conversion(
        self, image_class, mock_course, mock_topic, tmp_path
    ):
        """The regression: present on disk, but still a conversion output."""
        image = self._make(image_class, mock_course, mock_topic, tmp_path, create=True)
        image.mark_generated()
        assert image.execution_stage == COPY_GENERATED_IMAGES_STAGE

    def test_absent_image_is_still_treated_as_generated(
        self, image_class, mock_course, mock_topic, tmp_path
    ):
        """The pre-existing signal keeps working for uncommitted renders."""
        image = self._make(image_class, mock_course, mock_topic, tmp_path, create=False)
        assert image.execution_stage == COPY_GENERATED_IMAGES_STAGE


class TestCourseMarksGeneratedImages:
    """End-to-end over the real ``test-data`` course, which commits its PNGs."""

    def _image_named(self, course, name: str):
        matches = [f for f in course.files if f.path.name == name and "img" in f.path.parts]
        assert matches, f"no course file for img/{name}"
        return matches[0]

    @pytest.mark.parametrize("name", GENERATED_AND_COMMITTED)
    def test_committed_generated_images_wait_for_their_conversion(self, course_1, name):
        image = self._image_named(course_1, name)
        assert image.path.is_file(), (
            f"{name} is expected to be committed — that is the case this test covers"
        )
        assert image.execution_stage == COPY_GENERATED_IMAGES_STAGE, (
            f"img/{name} is rendered by a diagram source, so copying it in stage "
            f"{FIRST_EXECUTION_STAGE} races the conversion that overwrites it"
        )

    def test_static_images_still_copy_early(self, course_1):
        image = self._image_named(course_1, STATIC_ONLY)
        assert image.execution_stage == FIRST_EXECUTION_STAGE

    def test_every_diagram_output_is_marked_generated(self, course_1):
        """No diagram source may have its output left in the racing stage."""
        generated: set[Path] = set()
        for course_file in course_1.files:
            generated.update(course_file.source_outputs)
        assert generated, "test-data should contain at least one diagram source"

        stragglers = [
            f.path
            for f in course_1.files
            if f.path in generated and f.execution_stage == FIRST_EXECUTION_STAGE
        ]
        assert not stragglers, f"diagram outputs still scheduled in the racing stage: {stragglers}"
