"""Bearer-token authentication for the Worker API.

Every route the Worker API exposes mutates build state — claiming jobs,
reporting results, writing into the executed-notebook cache. Before this
module existed the API had no authentication at all, which meant two things:
anyone who could reach the port could drive a build, and any web page the
developer happened to have open could POST to it cross-origin (a
``fetch(..., {mode: 'no-cors'})`` with a simple content type needs no
preflight, and the handlers ignored content type).

The token closes both. It is a per-build secret generated by
:class:`~clm.infrastructure.api.server.WorkerApiServer` and injected into
worker containers through the environment, exactly as ``DB_PATH`` and
``CLM_API_URL`` already are. It must be presented as
``Authorization: Bearer <token>``; a ``?token=`` query parameter is
deliberately **not** accepted, because query strings land in access logs and
process listings.

The header requirement is also what defeats the cross-origin browser vector:
a page cannot set ``Authorization`` on a request without triggering a CORS
preflight, and the Worker API installs no CORS middleware, so the preflight
fails.

This module is **host-side only** — it imports FastAPI, which worker images do
not install. The token's name and generator live in
:mod:`clm.infrastructure.api.token` precisely so a worker can reach them
without reaching this.
"""

from __future__ import annotations

import logging
import secrets

from fastapi import HTTPException, Request, status
from fastapi.security.utils import get_authorization_scheme_param

logger = logging.getLogger(__name__)


def extract_bearer_token(request: Request) -> str | None:
    """Return the bearer token presented by ``request``, if any.

    Only the ``Authorization: Bearer <token>`` header is honoured. Unlike the
    Studio's ``extract_token``, this deliberately does not fall back to a
    ``?token=`` query parameter — there is no QR-code deep-link flow here, and
    a query parameter would leak the secret into uvicorn's access log.
    """
    header = request.headers.get("Authorization")
    if not header:
        return None
    scheme, param = get_authorization_scheme_param(header)
    if scheme.lower() != "bearer" or not param:
        return None
    return param


def token_matches(request: Request, expected: str) -> bool:
    """Constant-time check that ``request`` presents ``expected``."""
    presented = extract_bearer_token(request)
    if not presented:
        return False
    return secrets.compare_digest(presented, expected)


async def require_api_token(request: Request) -> None:
    """FastAPI dependency enforcing the per-build Worker API token.

    Attached to the worker router as a router-level dependency, so a route
    added later cannot forget it.

    Raises:
        HTTPException: 401 when the request presents no token or the wrong
            one. 500 when the app was somehow started without a token, which
            is a programming error — failing closed is the only safe answer.
    """
    expected = getattr(request.app.state, "api_token", None)
    if not expected:
        logger.error(
            "Worker API received a request but no token is configured on the app; "
            "refusing the request. This is a bug — WorkerApiServer always sets one."
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Worker API is misconfigured: no token",
        )

    if not token_matches(request, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid Worker API token",
            headers={"WWW-Authenticate": "Bearer"},
        )
